### ISSUE TITLE
Question - do databag items really need to be cached? 

### ISSUE THREAD

**Issue by spuder** [normanjoyner/data-bag-cache#1]
Two questions
1. This cookbook appears to have not been updated in a while. It is still relevant and maintained? 
2. Is it really needed? 

I have a cookbook that takes a long time to run (5 + minutes) and has multiple fetches of the same databags. One of the databags contains the build number, and developers update it multiple times a day through the api. From what I understand of chef, theoretically if a dev updates the databag while in the middle of a converge, bad things _could_ happen. 

Do I need to protect against these race conditions? Or is this not a problem?

**Comment by normanjoyner** [comment]
As I'm no longer using Chef, I haven't been maintaining this actively; however, I will continue to make necessary updates & fix issues as they are reported. This cookbook is **not** absolutely necessary. I created this for a previous job where we had hundreds of large data bag items which took quite a while to fetch (especially when not using Chef search). This cookbook optimizes fetching data bag items by leveraging search, as well as caching them in the case you are accessing the same data bag items from multiple cookbooks (where you could easily take advantage of an in memory cache to improve run time). This cookbook is really optimized for reads, as writes will not be reflected in the in cache, and a subsequent fetch using `cache_disabled` will be required to see those updates in the local cache. If you are not modifying data bags from your recipes, this could be a good way to prevent wonky behavior in the case of a developer updating a data bag mid Chef run, as it will operate on the data cached from the initial search.

**Comment by spuder** [comment]
Great thanks for the info. That does sound like exactly what I need.
